import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom' version '1.17.0-alpha.7'
    id 'com.modrinth.minotaur' version '2.+'
    id 'net.darkhax.curseforgegradle' version '1.+'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcap_version}"
    include "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcap_version}"
    compileOnly "com.electronwill.night-config:core:3.8.3"
    compileOnly "com.electronwill.night-config:toml:3.8.3"

    implementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${cca_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-base:${cca_version}"
    implementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${cca_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-entity:${cca_version}"
}

sourceSets {
    main {
        resources {
            srcDirs += '../licenses'
        }
    }
}

fabricApi {
    configureDataGeneration()
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = "${System.getenv('CURSEFORGE_KEY')}"
    def projectId = "${cf_id}".toString()
    def mainFile = upload(projectId, file("${project.layout.buildDirectory.get()}/libs/${base.archivesName.get()}-${version}.jar"))
    mainFile.changelogType = 'markdown'
    mainFile.changelog = file('../CHANGELOG_LATEST.md')
    mainFile.releaseType = "${release_type}"
    "${release_versions}".split(',').each {
        mainFile.addGameVersion("${it}")
    }
    mainFile.addRequirement("fabric-api")
    mainFile.withAdditionalFile(sourcesJar)

    doLast {

        if (project.hasProperty('cf_page') && mainFile.curseFileId != null) {
            project.ext.curse_link = "${cf_page}/files/${mainFile.curseFileId}"
        }
    }
}

modrinth {
    token = "${System.getenv('MODRINTH_KEY')}" ?: ""
    projectId = "${modrinth_id}"
    versionName = "${base.archivesName.get()}-${version}"
    versionType = "${release_type}"
    changelog = file('../CHANGELOG_LATEST.md').text
    uploadFile = file("${project.layout.buildDirectory.get()}/libs/${base.archivesName.get()}-${version}.jar")
    additionalFiles = [sourcesJar]
    gameVersions = "${release_versions}".split(",") as List<String>
    dependencies {
        required.project "fabric-api"
    }
}

tasks.modrinth.doLast {

    if (project.hasProperty('modrinth_page') && tasks.modrinth.newVersion != null) {
        project.ext.modrinth_link = "${modrinth_page}/version/${tasks.modrinth.newVersion.id}"
    }
}
