import javax.net.ssl.HttpsURLConnection
import java.nio.charset.StandardCharsets

plugins {
    // Required for NeoGradle
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.7"
}

def publishDiscord() {
    try {
        def links = ['curse_link', 'modrinth_link']
        def foundLinks = ['curse_link': new StringJoiner('\\n'), 'modrinth_link': new StringJoiner('\\n')]
        def modLoaders = []
        modLoaders.add(['neoforge', "NeoForge"])
        modLoaders.add(['fabric', "Fabric"])
        modLoaders.add(['forge', "Forge"])

        for (int i = 0; i < links.size(); i++) {
            def link = links[i]
            def currentLinks = foundLinks[link]

            for (int j = 0; j < modLoaders.size(); j++) {
                def modLoader = modLoaders[j]
                def id = modLoader[0]
                def name = modLoader[1]
                def foundLink = project(":${id}").findProperty("${link}")

                if (foundLink && currentLinks) {
                    currentLinks.add("[${name}](${foundLink})")
                }
            }
        }
        foundLinks.each {
            println("${it.getKey()}: ${it.getValue().toString()}")
        }
        def changelog = file("CHANGELOG_LATEST.md").getText()
        changelog = changelog.substring(changelog.indexOf("##"))
        changelog = changelog.replaceAll("\n", "\\\\n")

        if (changelog.length() >= 1024) {
            changelog = changelog.substring(0, 924)
            changelog = changelog + "...[(See more)](${changelog_link})"
        }
        println(changelog)
        int color = 65392

        if (release_type == "beta") {
            color = 16763904
        } else if (release_type == "alpha") {
            color = 16724273
        }
        final String message = """
            {
              "embeds": [
                {
                  "title": "${mod_name} ${version}",
                  "color": ${color},
                  "fields": [
                    {
                      "name": "Minecraft Versions",
                      "value": "${release_versions.replaceAll(",", ", ")}"
                    },
                    {
                      "name": "CurseForge",
                      "value": "${foundLinks['curse_link'].toString()}",
                      "inline": true
                    },
                    {
                      "name": "Modrinth",
                      "value": "${foundLinks['modrinth_link'].toString()}",
                      "inline": true
                    },
                    {
                      "name": "Changelog",
                      "value": "${changelog}"
                    }
                  ],
                  "thumbnail": {
                    "url": "${discord_thumbnail}"
                  }
                }
              ]
            }
            """
        println(message)
        final URL url = URI.create("${System.getenv('DISCORD_WEBHOOK')}").toURL()
        final HttpsURLConnection connection = (HttpsURLConnection) url.openConnection()
        connection.addRequestProperty("Content-Type", "application/json; charset=UTF-8")
        connection.addRequestProperty("User-Agent", "${mod_name} Gradle Upload")
        connection.setDoOutput(true)
        connection.setRequestMethod("POST")
        connection.connect()

        try (OutputStream out = connection.getOutputStream()) {
            out.write(message.getBytes(StandardCharsets.UTF_8))
        }
        connection.getInputStream().close()
        connection.disconnect()
    } catch (IOException e) {
        e.printStackTrace()
    }
}

def ordered(List<String> dependencyPaths) {
    def dependencies = dependencyPaths.collect { tasks.getByPath(it) }
    for (int i = 0; i < dependencies.size() - 1; i++) {
        dependencies[i + 1].mustRunAfter(dependencies[i])
    }
    return dependencies
}

tasks.register('publishMod') {
    def loaders = ['forge', 'fabric', 'neoforge']
    List<String> publishTasks = []
    loaders.each {
        publishTasks.add(":${it}:modrinth")
        publishTasks.add(":${it}:publishCurseForge")
    }
    dependsOn ordered(publishTasks)

    doLast {
        publishDiscord()
    }
}
