# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=15.0.0+26.1.2
group=com.illusivesoulworks.comforts
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Comforts
mod_author=Illusive Soulworks
mod_id=comforts
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/comforts/issues
sources_url=https://github.com/illusivesoulworks/comforts
description=Adds sleeping bags and hammocks for, respectively, portability and turning day to night, without setting new spawns.\nComes in 16 different colors!
minecraft_version_range=[26.1.2, 26.2)
minecraft_version_range_alt=~26.1.2

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# SpectreLib
spectrelib_version=0.21.0+26.1.2

# Fabric
fabric_version=0.148.0+26.1.2
fabric_loader_version=0.19.2
cca_version=8.0.0

# NeoForge
neoforge_version=26.1.2.71
neoforge_version_range=[26.1,)

# Publishing Options
cf_id=276951
cf_page=https://www.curseforge.com/minecraft/mc-mods/comforts
modrinth_id=SaCpeal4
modrinth_page=https://modrinth.com/mod/comforts
release_type=release
release_versions=26.1.2
changelog_link=https://github.com/illusivesoulworks/comforts/blob/26.1.x/CHANGELOG.md
discord_thumbnail=https://cdn.modrinth.com/data/SaCpeal4/ed4840f0c9a30e04ad88413bd82cd762dd6ec95d.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
