# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=12.0.0+1.21.8
group=com.illusivesoulworks.comforts
java_version=21

# Common
minecraft_version=1.21.8
mod_name=Comforts
mod_author=Illusive Soulworks
mod_id=comforts
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/comforts/issues
sources_url=https://github.com/illusivesoulworks/comforts
description=Adds sleeping bags and hammocks for, respectively, portability and turning day to night, without setting new spawns.\nComes in 16 different colors!
minecraft_version_range=[1.21.6, 1.22)
minecraft_version_range_alt=~1.21.6

# SpectreLib
spectrelib_version=0.18.2+1.21.8

# Parchment
parchment_mc=1.21.8
parchment_version=2025.09.14

# Fabric
fabric_version=0.136.0+1.21.8
fabric_loader_version=0.17.3
cca_version=7.0.0-beta.1

# Forge
forge_version=58.1.0
forge_version_range=[56,)

# NeoForge
neoforge_version=21.8.47
neoforge_version_range=[21.6,)

# Publishing Options
cf_id=276951
cf_page=https://www.curseforge.com/minecraft/mc-mods/comforts
modrinth_id=SaCpeal4
modrinth_page=https://modrinth.com/mod/comforts
release_type=release
release_versions=1.21.8,1.21.7,1.21.6
changelog_link=https://github.com/illusivesoulworks/comforts/blob/1.21.x/CHANGELOG.md
discord_thumbnail=https://cdn.modrinth.com/data/SaCpeal4/ed4840f0c9a30e04ad88413bd82cd762dd6ec95d.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
